// client/src/hooks/ghanaianFood.js

export const ghanaianFoodsRestaurants = [
  'KFC (Kentucky Fried Chicken)',
  'Burger King',
  'McDonald\'s',
  'Pizza Hut',
  'Domino\'s Pizza',
  'Papa\'s Pizza',
  'Pizza Inn',
  'Debonairs Pizza',
  'Chick-fil-A',
  'Subway',
  'Panda Express',
  'Starbucks',
  'Costa Coffee',
  'Café Kro',
  'Pizza Corner',
  'Kudobar',
  'Gourmet Kitchen',
  'Papaye Fast Food',
  'Burger and Relish',
  'Sahel Sahara',
  'Jezzy\'s Kitchen',
  'Angel\'s Kitchen',
  'Liften Foods',
  'Oga\'s Restaurant',
  'Buka Restaurant',
  'Asanka Local',
  'FAS Food & Drink',
  'DNR Fast Food',
  'Chopsticks Restaurant',
  'Nandos Ghana',
  'Nubuke Foundation Food Stall',
  'Food Inn',
  'Kelewele vendors',
  'Bistro 22',
  'The Food Shack',
  'Osei Kwame Despite Group’s Food Outlets',
  'Sky Plus Restaurant',
  'Coco Lounge',
  'The Lunch Box',
  'Yaa Asantewaa Restaurant',
  'The Kitchen Ghana',
  'Tandoor Restaurant',
  'Chickenman/Pizzaman',
  'Gold Coast Kenkey',
  'Kelewele (Spicy Fried Plantains)',
  'Kete (Sweet Coconut Snack)',
  'Kpekeke (Steamed Bean Cake)',
  'Kente (Sweet Corn Snack)',
  'Kumasi Koo (Local Ginger Drink)',
  'Gari Foto (Gari with Milk and Sugar)',
  'Bitter Kola Drink',
  'Milo (Chocolate Drink)',
  'Ogi (Fermented Corn Drink)',
  'Tamarind Juice'
];

export default ghanaianFoodsRestaurants;