// client/src/hooks/ghanaianFood.js

export const ghanaianFoodsRestaurants = [
  'KFC (Kentucky Fried Chicken)',
  'Burger King',
  'McDonald\'s',
  'Pizza Hut',
  'Domino\'s Pizza',
  'Papa\'s Pizza',
  'Pizza Inn',
  'Debonairs Pizza',
  'Chick-fil-A',
  'Subway',
  'Panda Express',
  'Starbucks',
  'Costa Coffee',
  'Café Kro',
  'Pizza Corner',
  'Kudobar',
  'Gourmet Kitchen',
  'Papaye Fast Food',
  'Burger and Relish',
  'Sahel Sahara',
  'Jezzy\'s Kitchen',
  'Angel\'s Kitchen',
  'Liften Foods',
  'Oga\'s Restaurant',
  'Buka Restaurant',
  'Asanka Local',
  'FAS Food & Drink',
  'DNR Fast Food',
  'Chopsticks Restaurant',
  'Nandos Ghana',
  'Nubuke Foundation Food Stall',
  'Food Inn',
  'Kelewele vendors',
  'Bistro 22',
  'The Food Shack',
  'Osei Kwame Despite Group’s Food Outlets',
  'Sky Plus Restaurant',
  'Coco Lounge',
  'The Lunch Box',
  'Yaa Asantewaa Restaurant',
  'The Kitchen Ghana',
  'Tandoor Restaurant',
  'Chickenman/Pizzaman',
  'Gold Coast Kenkey',
  'Kelewele (Spicy Fried Plantains)',
  'Kete (Sweet Coconut Snack)',
  'Kpekeke (Steamed Bean Cake)',
  'Kente (Sweet Corn Snack)',
  'Kumasi Koo (Local Ginger Drink)',
  'Gari Foto (Gari with Milk and Sugar)',
  'Bitter Kola Drink',
  'Milo (Chocolate Drink)',
  'Ogi (Fermented Corn Drink)',
  'Tamarind Juice',
    'Plantain with Kontomire Stew',
  'Plantain with Palava Sauce',
  'Plantain with Cabbage Stew',
  'Plantain with Garden Egg Stew',
  'Plantain with Light Soup',
  'Plantain with Groundnut Soup',
  'Plantain with Palm Nut Soup',
  'Plantain with Okro Stew',
  'Plantain with Tomato & Onion Stew',
  'Plantain with Beans Stew',
  'Plantain with Shito & Smoked Fish',
  'Plantain with Avocado & Fried Fish',
  'Plantain with Smoked Fish & Pepper Sauce',
  'Plantain with Coconut Fish Stew',
  'Plantain with Nkatie (Peanut) Sauce',
  'Plantain with Fried Egg & Tomato Stew',
  'Plantain with Grilled Tilapia & Shito',
  'Plantain with Agushi Stew',
  'Plantain with Ayoyo Soup',
  'Plantain with Mushroom Stew',
  'Cocoyam with Kontomire Stew',
  'Cocoyam with Palava Sauce',
  'Cocoyam with Garden Egg Stew',
  'Cocoyam with Cabbage Stew',
  'Cocoyam with Light Soup',
  'Cocoyam with Groundnut Soup',
  'Cocoyam with Palm Nut Soup',
  'Cocoyam with Okro Stew',
  'Cocoyam with Shito & Smoked Fish',
  'Cocoyam with Avocado & Fried Fish',
  'Cocoyam with Agushi Stew',
  'Cocoyam with Nkatie (Peanut) Sauce',
  'Yam with Kontomire Stew',
  'Yam with Palava Sauce',
  'Yam with Garden Egg Stew',
  'Yam with Cabbage Stew',
  'Yam with Light Soup',
  'Yam with Groundnut Soup',
  'Yam with Palm Nut Soup',
  'Yam with Okro Stew',
  'Yam with Tomato & Onion Stew',
  'Fried Yam with Shito & Fried Fish',
  'Yam with Avocado & Smoked Fish',
  'Yam with Agushi Stew',
  'Yam with Nkatie (Peanut) Sauce',
  'Yam with Grilled Tilapia & Pepper Sauce',
  'Yam with Coconut Fish Stew',
  'Fufu with Light Soup',
  'Fufu with Groundnut Soup',
  'Fufu with Palm Nut Soup',
  'Fufu with Abenkwan (Palm Nut Soup with Crab/Fish)',
  'Fufu with Okro Soup',
  'Fufu with Ayoyo Soup',
  'Fufu with Nkrakra (Light Soup with Okro)',
  'Fufu with Goat Meat Light Soup',
  'Fufu with Chicken Light Soup',
  'Fufu with Fish Light Soup',
  'Fufu with Mushroom Soup',
  'Fufu with Snail Light Soup',
  'Kokonte with Palm Nut Soup',
  'Kokonte with Groundnut Soup',
  'Kokonte with Light Soup',
  'Kokonte with Okro Stew',
  'Kokonte with Ayoyo Soup',
  'Kokonte with Abenkwan',
  'Kokonte with Fish Light Soup',
  'Kokonte with Goat Meat Light Soup',
  'Kokonte with Nkrakra',
  'Kokonte with Mushroom Soup',
  'Banku with Tilapia Pepper Soup',
  'Banku with Okro Stew',
  'Banku with Grilled Tilapia & Shito',
  'Banku with Fried Fish & Pepper Sauce',
  'Banku with Crab Stew',
  'Banku with Smoked Fish & Okro',
  'Banku with Light Soup',
  'Banku with Abenkwan',
  'Banku with Kenkey Style Pepper Sauce',
  'Banku with Fried Mackerel & Shito',
  'Rice with Stew & Fried Chicken',
  'Rice with Stew & Grilled Fish',
  'Rice with Beans (Red Red style)',
  'Rice with Groundnut Soup',
  'Rice with Palm Nut Soup',
  'Rice with Light Soup',
  'Rice with Okro Stew',
  'Rice with Garden Egg Stew',
  'Rice with Kontomire Stew',
  'Rice with Fried Egg & Shito',
  'Rice with Avocado & Smoked Fish',
  'Rice with Beef Stew',
  'Rice with Turkey Wings & Stew',
  'Fried Rice with Grilled Chicken',
  'Fried Rice with Fried Chicken',
  'Fried Rice with Beef Kebab',
  'Fried Rice with Grilled Tilapia',
  'Fried Rice with Shrimp',
  'Fried Rice with Mixed Grill (Chicken, Beef, Sausage)',
  'Fried Rice with Fried Fish',
  'Fried Rice with Turkey Wings',
  'Fried Rice with Gizzard',
  'Fried Rice with Coleslaw & Chicken',


  'Omotuo with Groundnut Soup',
  'Omotuo with Palm Nut Soup',
  'Omotuo with Light Soup',
  'Omotuo with Abenkwan',
  'Omotuo with Okro Soup',
  'Omotuo with Ayoyo Soup',
  'Omotuo with Mushroom Soup',
  'Omotuo with Goat Meat Light Soup',
  'Omotuo with Chicken Light Soup',
  'Omotuo with Fish Light Soup',

//   Porridges

  'Hausa Koko with Koose',
  'Hausa Koko with Puff-Puff',
  'Hausa Koko with Bread',
  'Hausa Koko with Meat Pie',
  'Hausa Koko with Fried Plantain',
  'Hausa Koko with Akara',
  'Hausa Koko with Sugar Bread',
  'Hausa Koko with Samosa',
  'Hausa Koko with Spring Rolls',

  // --- Tom Brown (Roasted Corn/Soya Porridge) Pairings ---
  'Tom Brown with Milk and Sugar',
  'Tom Brown with Evaporated Milk',
  'Tom Brown with Groundnuts',
  'Tom Brown with Bread',
  'Tom Brown with Koose',
  'Tom Brown with Puff-Puff',
  'Tom Brown with Coconut Flakes',
  'Tom Brown with Peanut Butter',
  'Tom Brown with Banana Slices',

  // --- Cocoa Tea (Hot Chocolate) Pairings ---
  'Cocoa Tea with Bread and Butter',
  'Cocoa Tea with Bread and Cheese',
  'Cocoa Tea with Meat Pie',
  'Cocoa Tea with Spring Rolls',
  'Cocoa Tea with Bofrot (Puff-Puff)',
  'Cocoa Tea with Toasted Bread',
  'Cocoa Tea with Scrambled Eggs',

  // --- Obrayo / Corn Porridge Pairings ---
  'Obrayo with Sugar and Milk',
  'Obrayo with Evaporated Milk',
  'Obrayo with Groundnuts',
  'Obrayo with Bread',
  'Obrayo with Koose',
  'Obrayo with Puff-Puff',
  'Obrayo with Coconut Flakes',
  'Obrayo with Roasted Peanuts',

  // --- Other Traditional Light Breakfasts ---
  'Nkatie Cake with Cocoa Tea',
  'Roasted Plantain with Nkatie',
  'Yakayake with Milk',
  'Lamugini with Bread',
  'Sobolo with Meat Pie',
  'Pap (Akamu) with Milk and Sugar',
  'Zomi (Corn Porridge) with Milk',
  'Koko with Koose',
  'Tom Brown with Koose',
  'Koko with Bread',

  // --- Urban & Modern Light Breakfasts ---
  'Avocado Toast with Poached Egg',
  'Fruit Salad with Yogurt',
  'Smoothie Bowl with Granola',
  'Oatmeal with Honey and Nuts',
  'Greek Yogurt with Fresh Berries',
  'Whole Wheat Bread with Peanut Butter',
  'Chicken Sandwich with Light Mayo',
  'Veggie Wrap with Hummus',
  'Pancakes with Maple Syrup',
  'Cereal with Milk and Banana',
  'Toast with Avocado and Tomato',
  'Scrambled Eggs with Toast',
  'French Toast with Honey',
  'Bagel with Cream Cheese',
  'Nkatie Cake (Peanut Brittle) with Cocoa Tea',
  'Roasted Plantain with Nkatie',
  'Yakayake with Milk',
  'Lamugini with Bread',
  'Sobolo with Meat Pie',
  'Fresh Fruit Salad with Yogurt',
  'Pap (Akamu) with Milk and Sugar',
  'Zomi (Corn Porridge) with Milk',
  // --- Savory Street Snacks (Chop Bar/Street Style) ---
  'Koose (Bean Cakes)',
  'Puff-Puff (Bofrot)',
  'Meat Pie',
  'Chicken Pie',
  'Fish Pie',
  'Samosa (Sambusa)',
  'Spring Rolls',
  'Gizzard Kebabs',
  'Chicken Kebab',
  'Beef Kebab',
  'Roasted Corn with Nkatie (Peanuts)',
  'Roasted Plantain with Nkatie',
  'Tubaani (Steamed Bean Pudding)',
  'Akara (Spicy Bean Balls)',
  'Yam Chips with Shito',
  'Plantain Chips',
  'Cassava Chips',
  'Fried Yam with Pepper Sauce',
  'Fried Plantain with Pepper Sauce',
  'Grilled Tilapia',
  'Smoked Fish with Pepper',
  'Nkate Cake (Peanut Brittle)',
  'Kuli-Kuli (Peanut Snack)',
  'Chinchinga (Suya)',
  'Hard Boiled Eggs with Salt & Pepper',
  'Scotch Eggs',
  'Sausage Rolls',
  'Vegetable Spring Rolls',
  'Fish Fingers',
  'Chicken Wings (Spicy)',
  
  // --- Sweet Snacks & Confectionery ---
  'Bofrot (Puff-Puff)',
  'Sugar Bread',
  'Coconut Candy',
  'Groundnut Candy',
  'Tamarind Candy',
  'Ice Kenkey (Sweetened Corn Dough)',
  'Fresh Coconut Water & Flesh',
  'Sugar Cane Juice',
  'Banana Chips',
  'Dried Mango Slices',
  'Pawpaw Slices',
  'Watermelon Slices',
  'Pineapple Slices',
  'Orange Slices',
  // --- Traditional Herbal & Grain Drinks ---
  'Sobolo (Hibiscus Drink)',
  'Asana (Fermented Corn Drink)',
  'Lamugini (Ginger Drink)',
  'Brukina (Millet Drink)',
  'Atadwe Milk (Tiger Nut Milk)',
  'Coconut Water',
  'Fresh Coconut Milk',
  'Palm Wine (Fresh)',
  'Pito (Traditional Millet Beer - Non-Alcoholic variant available)',
  'Zomi (Corn Porridge Drink)',
  'Hausa Koko',
  'Tom Brown',
  
  // --- Fruit Punches & Fresh Juices ---
  'Fresh Pineapple Juice',
  'Fresh Orange Juice',
  'Fresh Watermelon Juice',
  'Fresh Mango Juice',
  'Passion Fruit Juice',
  'Soursop (Graviola) Juice',
  'Baobab (Monkey Bread) Juice',
  'Tamarind Juice',
  'Lemon Grass Tea',
  'Mint Lemonade',
  'Ginger & Lemon Tea',
  'Mixed Fruit Punch',
  'Avocado Smoothie',
  'Papaya Smoothie',
  'Coconut & Pineapple Blend',
  
  // --- Modern/Urban Cafe Drinks ---
  'Iced Sobolo with Mint',
  'Ginger & Hibiscus Iced Tea',
  'Cold Brew Coffee',
  'Hot Chocolate (Cocoa Tea)',
  'Vanilla Latte',
  'Cappuccino',
  'Green Tea',
  'Chamomile Tea',
  'Sparkling Water with Lime',
  'Yoghurt Smoothie',
  'Detox Green Juice (Spinach, Apple, Ginger)'

];

export default ghanaianFoodsRestaurants;