// client/src/constants/searchConstants.js

export const SEARCH_MODES = {
  FOOD: 'food',
  RESTAURANT: 'restaurant'
};

export const GHANAIAN_FOODS = [
  'Jollof Rice',
  'Waakye',
  'Banku',
  'Fufu',
  'Kenkey',
  'Ampesi',
  'Tuo Zaafi',
  'Red Red',
  'Kelewele',
  'Plantain',
  'Yam Chips',
  'Fried Rice',
  'Plain Rice',
  'Beans Stew',
  'Groundnut Soup',
  'Light Soup',
  'Palm Nut Soup',
  'Okro Stew',
  'Kontomire Stew',
  'Gari Foto',
  'Abolo',
  'Tubaani',
  'Mpotompoto',
  'Omo Tuo',
  'Kelewele (Spicy Fried Plantains)',
  'Chinchinga (Kebab)',
  'Chips and Chibom (Bread and Eggs)',
  'Nut and Fruit Mix',
  'Roasted Cashews',
  'Groundnut (Peanuts)',
  'Kpekple (Steamed Bean Cakes)',
  'Abinbiro (Sweet Potato Balls)',
  'Kelewele with Peanuts',
  'Kobob (Grilled Meat Skewers)',
  'Ice Candy (Ice Lollies)',
  'Choco Milo Drink',
  'Susu (Milky Drink)',
  'Gari Foto (Gari with Spiced Milk)',
  'Popcorn',
  'Chips (Chipsi)',
  'Kokonte with Palm Nut Soup',
  'Akple and Fetri (Cornmeal Dumplings)',
  'Tsofi (Tapioca Balls)',
  'Bitterball (Sweet Coconut Balls)',
  'Kobor (Fried Groundnut Balls)',
  'Fried Fish Skewers',
  'Plantain Chips',
  'Kete (Sweet Coconut Snack)',
  'Kpekeke (Steamed Bean Cake)',
  'Kente (Sweet Corn Snack)',
  'Fried Plantain Chips',
  'Akara (Bean Cake)',
  'Kelewele with Ginger',
  'Palm Nut Candy',
  'Sobolo (Hibiscus Drink)',
  'Kalyppo (Fruit Juice)',
  'Nesquik Milk Drink',
  'Chibom (Milky Drink with Bread)',
  'Palm Wine',
  'Akpeteshie (Local Spirit)',
  'Pito (Locally Fermented Beer)',
  'Beer (Star, Club Beer, Gulder)',
  'Ting (Sparkling Water)',
  'Fanta',
  'Sprite',
  'Coca-Cola',
  'Minute Maid Orange Juice',
  'Capri-Sun Juice',
  'Fruit Juices (Mango, Pineapple, Banana, etc.)',
  'Nescafe (Coffee)',
  'Bottled Water (Eva, Voltic, Bel-Aqua)',
  'Ice Water with Lime',
  'Bissap (Hibiscus Drink)',
  'Zobo (Another Hibiscus Drink)',
  'Ginger Drink',
  'Lemonade',
  'Fruity Smoothies',
  'Yogurt Drinks (Actimel, Yakult)',
  'Hot Chocolate',
  'Milkshakes',
  'Coconut Water',
  'Kumasi Koo (Local Ginger Drink)',
  'Gari Foto (Gari with Milk and Sugar)',
  'Bitter Kola Drink',
  'Milo (Chocolate Drink)',
  'Ogi (Fermented Corn Drink)',
  'Tamarind Juice'

];

export const SPECIAL_KEYS = [
  'Breakfast',
  'Lunch', 
  'Dinner',
  'Snack',
  'Fruit',
];

export const RESTAURANT_NAMES = [
  // Fast Food Chains
  'KFC',
  'McDonald\'s',
  'Burger King',
  'Pizza Hut',
  'Domino\'s',
  'Subway',
  'Starbucks',
  'Chick-fil-A',
  'Taco Bell',
  'Wendy\'s',
  
  // Local Ghanaian Restaurants
  'Papaye',
  'Frankie\'s',
  'KFC Ghana',
  'Chicken Inn',
  'Pizza Man',
  'Maquis',
  'Bistro 22',
  'Santoku',
  'Mai Thai',
  'Asanka Local',
  'Polo Club',
  'Marina Beach Club',
  
  // Local Spots
  'Waakye Joint',
  'Chop Bar',
  'Street Food',
  'Gold Coast Kenkey',
  'Kenkey Shop',
  'Fufu Spot',
  
  // Healthy/Modern
  'Protein House',
  'Freshii',
  'Sweetgreen',
  'The Bowl',
  'Healthy Kitchen'
];

// Combined suggestions for food mode
export const FOOD_SUGGESTIONS = [SEARCH_MODES, GHANAIAN_FOODS, RESTAURANT_NAMES, SPECIAL_KEYS];